export const privacyPolicy = {
  en:`Memefy Privacy and Policy
  Last Updated: December 14, 2021
  We believe that you should always know what kind of data we collect from you, how we collect it, and how you can have control over your data. We strive to be transparent in our data collection efforts and to provide you with the data that you need to make decisions about our collection of data from you. This is the purpose of our privacy policy.
  
  
  There are certain things that you should be aware of when using our website and mobile applications.
  First, the Memefy website and mobile applications are publicly accessible and searchable to users and visitors around the world.
  This means that anything that you post to the Memefy website and mobile applications may be viewable by third parties.
  Second, since anything that you post to the Memefy website or mobile applications are tied to your user account, your postings may not be anonymous. If you prefer to protect your identity while using the Memefy website and mobile applications, we recommend that you use the service under a pseudonym.
  
  When you use the Memefy website and mobile applications, even if you are just browsing, we may collect some basic data from you such as the type of mobile device that you are using, your geographical location, and your IP address. If you choose to create a user account, you can choose to share additional data with us, which is outlined below. We also provide you with the ability to limit the data that we collect from you and how we use it.
  
  
  We also use your interactions with the Memefy website and mobile applications to show you more relevant content and to better understand how you interact with our service so that we can improve upon it. We may use your posts, comments, likes, shares, and mobile application activity to determine what kind of content you are interested in and to provide you with more of it and to improve upon our services.
  If you have any questions about our privacy policy, how we collect data from you, how we use your data, or how you can control your privacy settings, you can contact us at any time at contactmemefy@gmail.com.
  
  We may collect data from you when you voluntarily share it with us. This may include the following data:
  Account Data. You don’t have to create an account to use many of the Memefy website and mobile application features, such as viewing posts. If you do choose to create an account, however, you must provide us with some personal data so that we can provide you with the services that you have requested. This may include your username, password, email address, phone number, age, gender, contacts (when you invite friends from third party applications, such as Facebook or your mobile phone’s contacts application), and contact list.
  User-Generated Content. When you upload or submit content to the Memefy website or through the Memefy mobile application (“User-Generated Content”), we may use and publish your User-Generated Content to provide you and third parties with the Memefy website and mobile application services, to keep records of your communications or uploaded User-Generated Content on our services, to tailor content to your preferences, and to defend against legal claims.
  Public Data. Most of the information on the Memefy website and mobile applications is public. Most posts are public, the Memefy chat feature is public, and likes and comments are public. Memefy may use this public data to provide you with the services requested, to provide you with more relevant content, to tailor content to your preferences, to keep records of communications on our service, and to defend against legal claims.
  Private Communication Data. We may use your contact data, such as any data that you voluntarily provide to us like your phone number, email address, social media account handles, contacts, or contacts list, to authenticate your account, to communicate with you, to connect you with friends or other users, to invite your friends to MemeBit’s services at your request, to respond to communications sent to you by us, to keep records of our communication, or to pursue or defend against legal claims. We may store and process your private communications and data related to them to scan for malicious content, to detect spam or prohibited images, to review content for violations of our terms of use agreement, or to respond to legal process or law enforcement inquiries.
  Sensitive Personal Information (as defined by California law). We may use your sensitive personal information, such as the contents of your messages or text messages, to communicate with you, to connect you with friends or other users, and to respond to law enforcement requests, or to provide you with content that is relevant to your geographic location.
  
  We may also collect data from you automatically when you use the Memefy website or mobile applications. This may include the following data:
  Location Data. We may collect data about your location by collecting and processing your IP address and device settings. We may use this data to provide location-based services, tailor our services to your geographic location, respond to law enforcement requests, or to provide you with content that is relevant to your geographic location.
  Technical Data. We may collect technical data about your use of the Memefy website or mobile applications, such as your IP address, your device IDs, your IP address, the mobile application’s bundle ID, the ad or creative ID, your Memefy username, your phone number, pages visited, referring web page, your mobile phone model, mobile carrier, search terms, cookie data, your operating system, your geolocation, and your time zone. We may use this data to analyze your use of the Memefy website or mobile applications, to detect ad fraud or fraudulent impressions, to administer and secure our services, to determine how Memefy should allocate resources to its website or mobile applications, and to understand the technical load on Memefy's servers.
  Usage and Interaction Data. We may collect usage and interaction data from you when you use the Memefy website or mobile applications, such as recordings or logs of user screens within the Memefy mobile application or of the manner in which you interact with MemeBit’s website or mobile applications We may use this data to better tailor our services or to understand how we can improve our graphical user interfaces, which may include our remote configuration of the user interface of our mobile application to improve its functionality.
  Marketing Data. As a free service, we rely on advertisements to generate revenue to fund the Memefy website and mobile applications. We may collect your IP address, your application bundle ID, your advertising or creative ID, your Memefy user ID, your device IDs, your geographical location, your phone numbers, pages visited, referring web page, mobile phone model, search terms, cookie data, Google Advertising IDs, and Apple Advertising IDs. We may use your data to provide advertisements to you, to determine the relevance of advertisements, to measure the effectiveness of advertisements, to detect fraudulent advertisements or impressions, and to help make those advertisements more relevant to your preferences. When providing you with advertisements, we may transmit your personal data off of your device to third party advertisers so that they may serve relevant advertisements to you.
  Use of Cookies
  We may also collect data from you through the use of cookies and other technologies. This helps us understand how you use the Memefy website or mobile applications, serve you advertisements, and to understand any patterns that may be associated with your use of our services. This aids us in developing or improving our services in response to your needs or wants and in providing you with relevant offers from our advertisers.
  
  We may use session or persistent cookies. Session cookies are only stored on your computer or mobile device during your use of the Services and are automatically deleted when you close your web browser. Persistent cookies are stored as a file on your computer or mobile device that remain on your computer or mobile device even after you close your web browser. Persistent cookies can be read by the website that created the cookie when you revisit it again.
  We may use persistent cookies when we utilize Google Analytics or other analytics providers, which are intended to track the origin and behavior of traffic to the Memefy website and mobile applications. We may also, from time to time, receive data from third parties including analytics providers or advertising networks such as Google, Facebook, or Apple.
  We may send you marketing communications if you have asked us for information concerning our services or if you have agreed to, and have not opted out from, receiving marketing communications. You may ask us to stop sending you marketing messages at any time by logging into your account to adjust your marketing preferences or by following the opt-out link in any marketing message sent to you. In the event we sent you marketing text messages at your request, you may opt-out of receiving marketing text messages by texting STOP in response to any text message received from Memefy.
  Disclosure of Personal Data
  We only share or sell your personal data in limited circumstances.
  We may share, sell, or disclose your personal data with your consent or at your direction.
  We may also share or sell your data with certain third parties to aid us in operating the Memefy website or mobile applications. For example, we may share your personal data with third parties, such as analytics providers, to utilize their software tools and measure the effectiveness of our advertisements. We may also share or sell your personal data, such as device IDs, with third party advertisers to help them determine whether they should serve an ad to you. The data that we share with or sell to these third parties does not include your email address, name, phone number, or username, but it may include your geographical location.
  We may also share your personal data with our accountants, auditors, insurers, or attorneys where doing so is necessary to protect the interests of Memefy or to comply with any law or regulation.
  We may also share your personal data with government or law enforcement agencies when we are required to report our data processing activities, upon receipt of an exigent circumstances request, upon receipt of a duly authorized subpoena or court order, or where doing so is necessary to protect our users, our employees, our contractors, third parties, or property.
  Finally, we may share your personal data to a third party if we sell, transfer, or merge any part of our business or assets. In the event that we share your personal data in the sale, transfer, or merger of any part of our business or assets, this Privacy Policy will continue to apply to your personal data when transferred to the new entity.
  Chrysalid Limited is located in Africa. We may transfer your personal data to countries outside of the Africa, which may not offer the same level of protection. Many of our third-party service providers are located within the United States and their processing of personal data will involve an international transfer to several countries.
  We also put data security measures into place to protect your personal data. We allow access to your personal data only by employees and service providers who have a need to know or access your personal data on our instructions. We will notify you and any regulatory body of any breach of your personal data or our security measures if and when we are legally required to do so.
  We will only retain your personal data or sensitive personal data for so long as necessary to fulfill the purposes for which it is collected under this Privacy Policy or for the purposes of satisfying any legal, accounting, or reporting requirements.
  Subject’s Rights Article 18 of the LGPD provides the following rights: (i) confirmation of the existence of processing;
  (ii) access to data;
  (iii) correction of incomplete, inaccurate or out-of -date data; (iv) anonymization, blocking or deletion of unnecessary or excessive data or data processed in noncompliance with the Law; (v) portability of the data to another service provider or product provider; (vi) deletion of personal data processed with the consent of the data subject; (vii) information about public and private entities with which Memefy has shared data; (vii) information about the possibility of denying consent and the consequences of such denial; (viii) revocation of consent. To submit a request please email us at contactmemefy@gmail.com.
  You do not need to pay a fee to exercise your rights. We will apply our best efforts to briefly respond you in accordance with the deadlines established by LGPD.
  To confirm your request, we may need to request specific information from you as a security measure to ensure that personal data is not disclosed to an unauthorized third party.
  Third Party Links
  Our services may include links to third party websites and applications. By clicking on third party links, you may allow third parties to collect or share data about you. We do not control these third-party links and you are advised their respective privacy policies.
  Responding to Do Not Track Signals
  You can generally opt-out of receiving personalized ads from third party advertisers and ad networks who are members of the Network Advertising Initiative (NAI) or who follow the Digital Advertising Alliance’s Self-Regulatory Principles for Online Behavioral Advertising by visiting the opt-out pages on the NAI website and DAA website. Our websites are not currently set up to respond to browser do-not-track signals, but you can configure your browser settings to reject all cookies or prompt you before a cookie is set.
  Notification of Changes in the Privacy Policy
  Subject to the application of your rights under the applicable legal provisions, we reserve the right to modify this Privacy Policy without notice in order to reflect technological developments, legislative and regulatory changes and good business practices. In the event that we change our Privacy Policy, an updated version of this Policy will reflect those changes and we will notify you of those changes by changing the effective date at the top of this Policy and other places that we deem appropriate.
  Children Prohibited
  Our services are not directed to, or open to, children under the age of 13. In using our services, you warrant that you are over the age of twelve (13). If you are younger than 13, please do not use the MemeBit website or mobile applications and please do not provide personal data to us.
  Global Operations You understand and agree that we may store and process your data on computers located outside of the Brazilian territory, including, but not limited to, in the United States, European Union and the Russian Federation. By using the the Memefy website and mobile applications, you agree to the collection and processing of your data outside of the Brazilian territory.
  
  Contact Information:
  If you have any questions or suggestions regarding our Privacy Policy, or if your personal information is not accurate or complete, please contact our Data Protection Officer at:
  Memefy Inc.
  contactmemefy@gmail.com`,
  fr:`Memefy Privacy and Policy
  Last Updated: December 14, 2021
  Nous croyons que vous devriez toujours savoir quel type de données nous recueillons de votre part, comment nous la recueillons et comment vous pouvez contrôler vos données. Nous nous efforçons d'être transparents dans nos efforts de collecte de données et de vous fournir les données que vous devez prendre des décisions concernant notre collecte de données de votre part. C'est le but de notre politique de confidentialité.
  
  
  Il y a certaines choses que vous devriez être au courant de l'utilisation de notre site Web et de nos applications mobiles.
  Premièrement, le site Web Memefy et les applications mobiles sont accessibles au public et à la recherche d'utilisateurs et de visiteurs du monde entier.
  Cela signifie que tout ce que vous postez sur le site Web Memefy et les applications mobiles peut être visible par des tiers.
  Deuxièmement, étant donné que tout ce que vous postez sur le site Web Memefy ou les applications mobiles sont liés à votre compte d'utilisateur, vos messages peuvent ne pas être anonymes. Si vous préférez protéger votre identité lors de l'utilisation du site Web Memefy et des applications mobiles, nous vous recommandons d'utiliser le service sous un pseudonyme.
  
  Lorsque vous utilisez le site Web Memefy et les applications mobiles, même si vous ne faites que naviguer, nous pouvons collecter des données de base à partir de votre part, telles que le type de périphérique mobile que vous utilisez, votre emplacement géographique et votre adresse IP. Si vous choisissez de créer un compte d'utilisateur, vous pouvez choisir de partager des données supplémentaires avec nous, qui est décrite ci-dessous. Nous vous fournissons également la possibilité de limiter les données que nous recueillons de vous et de la manière dont nous l'utilisons.
  
  
  Nous utilisons également vos interactions avec le site Web Memefy et les applications mobiles pour vous montrer de contenu plus pertinent et mieux comprendre comment vous interagissez avec notre service afin que nous puissions l'améliorer. Nous pouvons utiliser vos messages, vos commentaires, vos goûts, des actions et vos applications mobiles pour déterminer le type de contenu qui vous intéresse et pour vous en fournir davantage et améliorer nos services.
  Si vous avez des questions sur notre politique de confidentialité, la manière dont nous collectons des données de votre part, comment nous utilisons vos données ou comment contrôler vos paramètres de confidentialité, vous pouvez nous contacter à tout moment à contactmemefy@gmail.com.
  
  Nous pouvons collecter des données de votre part lorsque vous les partagez volontairement avec nous. Cela peut inclure les données suivantes:
  Données de compte. Vous n'avez pas besoin de créer un compte pour utiliser de nombreuses fonctionnalités de site Web Memefy et d'applications mobiles, telles que la visualisation des messages. Si vous choisissez de créer un compte, vous devez vous fournir certaines données personnelles afin que nous puissions vous fournir les services que vous avez demandés. Cela peut inclure votre nom d'utilisateur, votre mot de passe, votre adresse e-mail, votre numéro de téléphone, votre âge, un sexe, des contacts (lorsque vous invitez des amis à partir d'applications tierces, telles que Facebook ou votre application de contacts de votre téléphone mobile), ainsi que la liste de contacts.
  Contenu généré par l'utilisateur. Lorsque vous téléchargez ou soumettez du contenu au site Web Memefy ou sur l'application Memefy Mobile ("Contenu généré par l'utilisateur"), nous pouvons utiliser et publier votre contenu généré par l'utilisateur pour vous fournir des tiers et les tiers avec le site Web MemeBit et les services d'application mobile, afin de conserver des enregistrements de vos communications ou de télécharger.
  Données publiques. La plupart des informations sur le site Web Memefy et les applications mobiles sont publiques. La plupart des messages sont publics, la fonction de discussion Memefy est publique, les réactions ("rire", "coeur", "cool"...) et les commentaires sont publics. Memefy peut utiliser ces données publiques pour vous fournir les services demandés, afin de vous fournir un contenu plus pertinent, de personnaliser le contenu de vos préférences afin de conserver des enregistrements de communication sur notre service et de se défendre contre les revendications juridiques.
  Données de communication privées. Nous pouvons utiliser vos données de contact, telles que toutes les données que vous nous fournissez volontairement, telles que votre numéro de téléphone, votre adresse électronique, des poignées de compte de média social, des contacts ou des contacts, pour authentifier votre compte, pour vous connecter avec vous, pour vous connecter avec des amis ou d'autres utilisateurs, pour inviter vos amis à Memefy's Nous pouvons stocker et traiter vos communications privées et vos données qui leur sont liées pour numériser pour un contenu malveillant, détecter les images de spam ou interdites, à examiner le contenu des violations de nos conditions d'utilisation, ou à répondre aux enquêtes juridiques ou aux demandes d'application de la loi.
  Informations personnelles sensibles (telles que définies par la loi de la Californie). Nous pouvons utiliser vos informations personnelles sensibles, telles que le contenu de vos messages ou des messages texte, pour vous communiquer avec vous, pour vous connecter avec des amis ou d'autres utilisateurs, ainsi que de répondre aux demandes d'application de la loi ou de vous fournir du contenu pertinent pour votre emplacement géographique.
  
  Nous pouvons également collecter des données à partir de votre part automatiquement lorsque vous utilisez le site Web Memefy ou les applications mobiles. Cela peut inclure les données suivantes:
  Données de localisation. Nous pouvons collecter des données sur votre emplacement en collectant et en traitement de votre adresse IP et de vos paramètres de périphérique. Nous pouvons utiliser ces données pour fournir des services basés sur l'emplacement, adapter nos services à votre lieu géographique, répondre aux demandes de la force publique ou vous fournir un contenu pertinent pour votre emplacement géographique.
  Données techniques. Nous pouvons collecter des données techniques sur votre utilisation du site Web Memefy ou des applications mobiles, telles que votre adresse IP, votre ID de périphérique, votre adresse IP, votre identifiant de paquetage de l'application mobile, votre identifiant d'annonce ou créatif, votre nom d'utilisateur Memefy, votre numéro de téléphone, des pages visitées, de votre numéro de téléphone. Nous pouvons utiliser ces données pour analyser votre utilisation du site Web Memefy ou des applications mobiles, de détecter les impressions de fraude publicitaires ou frauduleuses, à administrer et à sécuriser nos services, afin de déterminer comment Memefy devrait allouer des ressources à son site Web ou à ses applications mobiles et à comprendre la charge technique sur les serveurs de Memefy.
  Données d'utilisation et d'interaction. Nous pouvons collecter des données d'utilisation et d'interaction à partir de vous lorsque vous utilisez le site Web Memefy ou les applications mobiles, telles que des enregistrements ou des journaux des écrans utilisateur dans l'application Memefy Mobile ou de la manière dont vous interagissez avec le site Web ou les applications mobiles de Memefy, nous pouvons utiliser ces données pour mieux adapter nos services ou
  Données marketing. En tant que service gratuit, nous nous appuyons sur des publicités pour générer des revenus pour financer le site Web Memefy et les applications mobiles. Nous pouvons collecter votre adresse IP, votre identifiant d'appui de votre candidature, votre identifiant de publicité ou votre identifiant de création, votre ID utilisateur Memefy, votre ID de périphérique, votre emplacement géographique, vos numéros de téléphone, des pages visitées, une page de références Web, un modèle de téléphone mobile, des termes de recherche, des données de cookie, des identifiants de la publicité Google, et Nous pouvons utiliser vos données pour vous fournir des publicités afin de déterminer la pertinence des publicités, de mesurer l'efficacité des publicités, de détecter des publicités ou des impressions frauduleuses et de faire plus de pertinence de ces annonces pour vos préférences. Lorsque vous vous fournissez des publicités, nous pouvons transmettre vos données personnelles de votre appareil à des annonceurs tiers afin qu'ils puissent servir des publicités pertinentes pour vous.
  Utilisation des Cookies
  Nous pouvons également collecter des données de votre part grâce à l'utilisation de cookies et d'autres technologies. Cela vous aide à comprendre comment vous utilisez le site Web Memefy ou les applications mobiles, vous servez de publicités et de comprendre les modèles pouvant être associés à votre utilisation de nos services. Cela nous aident à développer ou à améliorer nos services en réponse à vos besoins ou à vos besoins et à vous fournir des offres pertinentes de nos annonceurs.
  
  Nous pouvons utiliser des cookies de sessions ou des cookies persistants. Les cookies de session ne sont stockés que sur votre ordinateur ou votre appareil mobile lors de votre utilisation des services et sont automatiquement supprimés lorsque vous fermez votre navigateur Web. Les cookies persistants sont stockés comme un fichier sur votre ordinateur ou votre appareil mobile qui restent sur votre ordinateur ou votre appareil mobile, même après la fermeture de votre navigateur Web. Les cookies persistants peuvent être lus par le site Web qui a créé le cookie lorsque vous le revisitez à nouveau.
  Nous pouvons utiliser des cookies persistants lorsque nous utilisons Google Analytics ou d'autres prestataires d'analyses, destinés à suivre l'origine et le comportement du trafic sur le site Web MemeBit et les applications mobiles. Nous pouvons également recevoir des données de tiers, notamment des fournisseurs d'analyses ou des réseaux publicitaires tels que Google, Facebook ou Apple.
  Nous pouvons vous envoyer des communications marketing si vous nous avez posé des informations sur nos services ou si vous avez choisi de recevoir des communications marketing. Vous pouvez nous demander d'arrêter de vous envoyer des messages marketing à tout moment en vous connectant à votre compte pour ajuster vos préférences marketing ou en suivant le lien de désinscription dans tout message de marketing envoyé. Si nous vous avons envoyé des messages texte marketing à votre demande, vous pouvez désactiver la réception de messages texte marketing en textos sur une butée en réponse à tout message texte reçu de Memefy.
  Divulgation de données personnelles
  Nous ne partageons ou ne vendons que vos données personnelles dans des circonstances limitées.
  Nous pouvons partager, vendre ou divulguer vos données personnelles avec votre consentement ou votre direction.
  Nous pouvons également partager ou vendre vos données avec certains tiers pour nous aider à utiliser le site Web Memefy ou les applications mobiles. Par exemple, nous pouvons partager vos données personnelles avec des tiers, tels que les fournisseurs d'analyses, pour utiliser leurs outils logiciels et mesurer l'efficacité de nos annonces. Nous pouvons également partager ou vendre vos données personnelles, telles que des ID de périphérique, avec des annonceurs tiers pour les aider à déterminer s'ils devraient vous servir une annonce. Les données que nous partageons ou vendons à ces tiers n'incluent pas votre adresse électronique, votre nom, votre numéro de téléphone ou votre nom d'utilisateur, mais cela peut inclure votre emplacement géographique.
  Nous pouvons également partager vos données personnelles avec nos comptables, les auditeurs, les assureurs ou les avocats, dans la mesure du possible pour protéger les intérêts de Memefy ou de se conformer à toute loi ou réglementation.
  Nous pouvons également partager vos données personnelles avec des agences gouvernementales ou des forces de l'ordre lorsque nous devons faire rapport de nos activités de traitement de données, à la réception d'une demande de circonstance exigente, à la réception d'une assignation de conseil ou d'une ordonnance du tribunal dûment autorisée, ou si cela est nécessaire pour protéger nos utilisateurs, nos employés, notre contrat.
  Enfin, nous pouvons partager vos données personnelles à une tierce partie si nous vendions, transférons ou fusionner une partie de notre entreprise ou de nos actifs. Si nous partageons vos données personnelles dans la vente, le transfert ou la fusion de toute partie de notre entreprise ou de notre actif, cette politique de confidentialité continuera de s'appliquer à vos données personnelles lorsqu'elles sont transférées à la nouvelle entité.
  Chrysalid Limited est situé en Afrique. Nous pouvons transférer vos données personnelles vers des pays situés à l'extérieur de l'Afrique, ce qui peut ne pas offrir le même niveau de protection. Beaucoup de nos fournisseurs de services tiers sont situés aux États-Unis et leur traitement de données à caractère personnel impliquera un transfert international dans plusieurs pays.
  Nous mettons également des mesures de sécurité de données en place pour protéger vos données personnelles. Nous autorisons uniquement l'accès à vos données personnelles uniquement par les employés et les fournisseurs de services qui ont besoin de connaître ou d'accéder à vos données personnelles sur nos instructions. Nous vous informerons et tout organe de réglementation de toute violation de vos données personnelles ou de nos mesures de sécurité si et lorsque nous sommes légalement tenus de le faire.
  Nous ne conserverons que vos données personnelles ou vos données personnelles sensibles aussi longtemps que nécessaire pour remplir les objectifs pour lesquels elle est collectée en vertu de la présente politique de confidentialité ou pour répondre aux exigences légales, comptables ou de rapport.
  Les droits du sujet L'article 18 de la LGPD fournit les droits suivants: (i) confirmation of the existence of processing;
  (ii) accès aux données;
  (iii) correction des données incomplètes, inexactes ou sortantes de -date;
  (iv) l'anonymisation, le blocage ou la suppression des données ou des données inutiles ou excessives traitées dans la non-conformité avec la loi; (v) Portabilité des données à un autre fournisseur de services ou fournisseur de produits; (vi) Suppression des données personnelles traitées avec le consentement du sujet des données; (vii) information about public and private entities with which Memefy has shared data; (vii) informations sur la possibilité de nier le consentement et des conséquences de ce déni; (viii) révocation du consentement. Pour soumettre une demande, veuillez nous envoyer un courriel à contactmemefy@gmail.com
  Vous n'avez pas besoin de payer des frais pour exercer vos droits. Nous appliquerons nos meilleurs efforts pour vous répondre brièvement conformément aux délais établis par LGPD.
  Pour confirmer votre demande, nous devrions peut-être demander des informations spécifiques de votre part en tant que mesure de sécurité pour que les données à caractère personnel ne soient pas divulguées à une tierce partie non autorisée.
  Liens vers des tiers
  Nos services peuvent inclure des liens vers des sites Web et des applications tiers. En cliquant sur des liens de`
};




export const termsOfService = {
  en:`Welcome and thank you for visiting and using Memefy.
  Last Updated : 12 December 2021
  By accessing or using any of the Services provided by Memefy or its affiliates, however accessed, you (collectively with Memefy, the “Parties”) manifest your intent and agree to be bound by this terms of use Agreement (“Agreement”). This Agreement affects your legal rights and obligations. If you do not agree to be bound by this Agreement, you are expressly prohibited from accessing or using the Services. After a modification, replacement, or amendment of the terms of this Agreement, your continued use of the Services constitutes your agreement to said modification, replacement, or amendment.
  Eligibility
  The Services are only available to individuals above the age of eighteen (13) and older, whichever is greater. Individuals under the age of 13 are expressly prohibited from creating a user account or otherwise using the Services. Memefy may provide Users with the ability to upload or transmit content to or through the Services, including, but not limited to, User Engagement. When you submit User Engagement to the Services, you grant MemeBit a non-exclusive, irrevocable, worldwide, and perpetual license to use your User Engagement for the customary and intended purposes of the Services. These purposes may include providing you or third parties with the Services, backing up or archiving the Services, and selling or transferring the Services to a third party. In submitting User Engagement to the Services, you agree to waive all moral rights in or to your User Engagement across the world, whether you have or have not asserted moral rights. You also agree to waive all rights of publicity or privacy in or to your User Engagement.
  Memefy is not responsible for any User Engagement, third-party content, syndicated content, services, advertisements, and/or links that may be contained on the Services. The Services may contain links to third party websites that are not owned or controlled by Memefy. Memefy has no control over, and assumes no responsibility for, the content, services, privacy policies, terms of use, or practices of any third-party websites or services. Additionally, Memefy will not and cannot censor or edit the content of any third-party site. By using the Services, you expressly hold Memefy harmless from any and all liability arising from your use of any third-party website. YOUR CORRESPONDENCE AND BUSINESS DEALINGS WITH THIRD PARTIES FOUND THROUGH THE SERVICES ARE SOLELY BETWEEN YOU AND THE THIRD PARTY.
  You agree that you are responsible for all data or roaming charges you incur through use of the Services.
  Memefy prohibits crawling, scraping, caching or otherwise accessing any Content or User Engagement on the Memefy Service via automated means, except as may be the result of standard search engine protocols or technologies used by a search engine with Memefy express consent.
  You are solely responsible for your interactions with other Users of the Services, whether online or offline. You agree that Memefy is not responsible or liable for the conduct of any User. Memefy reserves the right, but has no obligation, to monitor or become involved in disputes between you and other Users.
  There will be occasions when the Services may be interrupted, including, without limitation, for scheduled maintenance or upgrades, for emergency repairs, or due to failure of telecommunications links and/or equipment. Memefy will not be held responsible for any such interruptions.
  Memefy reserves the right to remove any Content and/or User Engagement from the Services for any reason, without prior notice. Content and/or User Engagement removed from the Services may continue to be stored by Memefy, including, without limitation, in order to comply with certain legal obligations, but may not be retrievable without a valid court order. Memefy is not a backup service and you agree that you will not rely on the Services for the purposes of content backup or storage. Memefy will not be liable to you for any modification, suspension, or discontinuation of the Memefy Services or the loss of any Content or User Engagement. You also acknowledge that the Internet may be subject to breaches of security and that the submission of User Engagement or other information may not be secure. You are expressly and solely responsible for your own security when using the Services.
  Memefy provides you with a limited, non-exclusive, non-sublicensable, non-assignable, and revocable license to use the Services for their customary and intended purposes. Use of the Services for a use outside of their customary and intended purposes or in violation of the terms of this Agreement will result in the immediate termination of this license. This license is revocable at any time, and any rights not expressly granted herein are reserved to MemeBit.
  In order to access some features of the Services, you will have to create an account. You may never use another User's account without permission or solicit, collect, or use the login credentials of other Users. When creating your account, you must provide accurate and complete information. You are responsible for keeping your password secure and you are solely responsible for the activity that occurs on your account. Although Memefy will not be liable for any losses caused by any unauthorized use of your account, you may be liable for the losses of MemeBit or others due to such unauthorized use. If you become aware of any breach of security or unauthorized use of your password or of your account, you must notify Memefy immediately at contactmemefy@gmail.com.
  You agree you will not sell, transfer, license or assign your account, username, or any account rights. Memefy prohibits the creation of, and you agree that you will not create, an account for anyone other than yourself.
  You also agree that all information you provide or have provided to Memefy upon registration and at all other times will be true, accurate, current, and complete, and you agree to update your information as necessary to maintain its truth and accuracy.
  Use of the Services--Permissions and Restrictions on Your Use
  You agree to use the Services only for purposes that are permitted by this Agreement. Memefy here by grants you permission to access and use the Services as set forth in this Agreement, provided that:
  You agree that you have the legal right and capacity to enter into this Agreement in your jurisdiction.
  You must not use the Services for any illegal or unauthorized purpose. You agree to comply with all laws, rules and regulations (e.g., federal, state, local and provincial) applicable to your use of the Services and your User Engagement, including, but not limited to, copyright laws and export laws.
  You must not post abusive, obscene, threatening, harassing, defamatory, libelous, offensive, violent, nude, partially nude, discriminatory, unlawful, infringing, hateful, pornographic, or sexually suggestive User Engagement via the Services, or User Engagement that encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise inappropriate. You must not post spam. You must not defame, stalk, bully, abuse, harass, threaten, impersonate or intimidate people or entities. You must not intentionally make false or misleading statements.
  You must not post private, confidential or sensitive information, or information that is otherwise in breach of the law via the iServices, including, without limitation, your or any other person's credit card information, social security, or national identity numbers, non-public phone numbers, addresses, or email addresses. You must not submit material that is copyrighted, protected by trade secret, or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from their rightful owner to post the material and to grant to Memefy all of the licensed rights granted herein.
  You must keep all of your User Engagement relevant and "on topic" to the particular item of User Engagement open for comments or submissions.
  You must not distribute in any medium any part of the Services without prior written authorization from MemeBit. You agree not to circumvent, disable or otherwise interfere with security related features of the Services or features that prevent or restrict use or copying of any Content and User Engagement or enforce limitations on use of the Services and the Content and User Engagement therein.
  You must not engage in any activity that interferes with or disrupts the Services (or the servers and networks which are connected to the Services), including by transmitting any worms, viruses, spyware, malware, or any other code of a destructive or disruptive nature. You may not inject content or code or otherwise alter or interfere with the way any part of the Services is rendered or displayed in a User's browser or device.
  You must not change, alter or modify any part of the Services for any reason.
  You agree not to use or launch any type of automated system, including but not limited to, "robots," "spiders," or "offline readers," that accesses the Services in a manner that sends more request messages to Memefy's servers in a given period of time than a human can reasonably produce in the same period by using a conventional on-line web browser. You agree not to access(or attempt to access) any of the Services, including Content and User Engagement, by any means other than through the interfaces that are provided by Memefy.
  You must not solicit, for commercial purposes, spam, or send harassing communications to any Users. Additionally, you must not collect or harvest any personal information from the Services.
  You must not attempt to restrict another User from using or enjoying the Services and you must not encourage or facilitate violations of this Agreement or any other MemeBit terms.
  The Content and Memefy intellectual property, including, but not limited to, the Memefy trademarks, trade names, and logos, on the Services are owned by or licensed to Memefy, subject to copyright and other intellectual property rights under United States and foreign laws and international conventions. Content on the Services may not be used, copied, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for any other purposes whatsoever without the prior written consent of the respective owners. Memefy reserves all rights that are not expressly granted in and to the Services and the Content.
  You agree not to use, copy, or distribute, either directly or indirectly, any of the Content other than that which is expressly permitted herein, including any use, copying, or distribution of User Engagement of third parties obtained through the Services for any commercial purposes. If you download or print a copy of the Content and/or User Engagement for personal use, you must retain all copyright and other proprietary notices contained therein. You agree that Memefy holds no responsibility for content posted within the service, including, but not limited to, User Engagement. Memefy is not obligated to monitor or edit any content posted on Memefy, including, but not limited to, User Engagement. If your content violates this Agreement, you may bear legal responsibility for that content.
  Memefy reserves the right to discontinue any aspect of the Services, either specifically to you or generally, at any time.
  Memefy may terminate a User's access to the Services at any time, for any reason. If MemeBit suspects that you have violated any provision of this Agreement, Memefy may also seek any other available legal remedy. Your rights under this Agreement will terminate automatically if you breach any part of this Agreement. Further, Memefy reserves the right to refuse access to the Services to anyone for any reason at any time.
  User Engagement
  You may be given the opportunity to review and post User Comments on the Services. Your User Comments must adhere to this Agreement, any additional applicable terms of the mobile application store or marketplace where you have downloaded such Services, and, to the extent applicable, foreign, national, state, or local laws. If a comment is made using your identity, it will be deemed to have been posted by you. Memefy will not accept responsibility for User Comments and other information posted in the comments. If Memefy receives notice that any User Comments are not in compliance with this Agreement or the intended use of the User Comments, MemeBit may remove such User Comments. Additionally, engaging in such conduct may result in you and/or your account being banned from the Services.
  User Comments are made available to you for your information and personal use solely as intended through the normal functionality of the Services. User Comments are made available AS IS and may not be used, copied, reproduced, displayed, sold, licensed, downloaded, distributed, transmitted, broadcast, or otherwise exploited in any manner not intended by the normal functionality of the Services or otherwise as expressly authorized under this Agreement.
  You own or have the necessary licenses, rights, consents, and permissions to use and authorize us to use all patent, trademark, trade secret, copyright or other proprietary rights in and to any and all User Submissions to enable inclusion and use of the User Submissions in the manner contemplated by the Services and this Agreement.
  You have the written consent, release, and/or permission of each and every identifiable individual person in the User Submission to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of the User Submissions in the manner contemplated by the Services and this Agreement.
  You additionally affirm, represent, and warrant that the posting and use of your User Engagement on or through the Memefy Services does not violate, misappropriate or infringe on the rights of any third party, including, without limitation, privacy rights, publicity rights, copyrights, trademark and/or other intellectual property rights.
  You agree to pay for all royalties, fees, and any other monies owed by reason of your User Engagement that you post on or through the Services.
  Memefy does not endorse any User Engagement or any opinion, recommendation, or advice expressed therein, and MemeBit expressly disclaims any and all liability in connection with User Engagement. Memefy does not permit copyright infringing activities and infringement of intellectual property rights on its Services, and Memefy will remove all Content and User Engagement if properly notified that such Content or User Engagement infringes on another's intellectual property rights. Memefy may, but has no obligation to, remove, edit, block, and/or monitor User Engagement or accounts containing User Engagement that MemeBit determines in its sole discretion violates this Agreement. Memefy will also terminate a User's access to the Services, if they are determined to be a repeat infringer. A repeat infringer is a User who has been notified of infringing activity more than twice and/or has had User Engagement removed from the Services more than twice.
  MemeBit reserves the right to determine in its sole discretion whether Content or User Engagement is appropriate and complies with this Agreement for violations other than copyright infringement and violations of intellectual property law, including, but not limited to, pornography, obscene or defamatory material, hate speech, or excessive length. Memefy may, at any time, without prior notice and in its sole discretion remove such User Engagement and/or terminate a User's access for submitting such material in violation of this Agreement.
  You understand that when using the Services, you will be exposed to User Engagement from a variety of sources. Memefy is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such User Engagement. You understand and agree that MemeBit cannot and will not be responsible for the User Engagement posted on the Services and you use the Services at your own risk.
  Memefy may provide you with the ability to share your geographical location with Memefy and other users of the Services when using the Services. You may also accept or reject any requests from users of the Services to obtain your geographical location through the Services. If you share your geographical location with your subscribers, you understand and agree that your geographical location may appear on a map and that subscribers to your Memefy account may be able to determine your exact, physical location. If you utilize the Services to post User Engagement to the MemeBit map feature located within the Services, you understand and agree that your geographical location may appear on a map and that all users of the MemeBit map feature located within the Services may be able to determine your exact, physical location. Memefy provides you with the opportunity to opt-in and opt-out of sharing your geographical location within the settings of your mobile device and/or web browser, which may provide you with several options for the sharing of your geographical location, such as options to share your geographical location at all times, only when using the iServices, or never. Should you wish to cease the sharing and use of your geographic location by Memefy, you are advised to disable location services within the settings of your mobile device and/or web browser. If you do not share your physical location with the Services, you may not use the Memefy map feature located within the Services.
  
  You agree to defend, indemnify and hold harmless the Memefy Parties from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including, but not limited to, attorney's fees) arising out of or in any way connected with:
  (i) your User Engagement or your use of and access to the Memefy Services;
  (ii) your breach or alleged breach of this Agreement;
  (iii) your violation or alleged violation of any third party right, including without limitation any intellectual property right, publicity, confidentiality, property or privacy right;
  (iv) your violation or alleged violation of any laws, rules, regulations, codes, statutes, ordinances or orders;
  (v) any claim that your User Engagement caused damage to a third party; or
  (vi) any misrepresentation made by you. You will cooperate as fully required by Memefy in the defense of any claim.
  
  Memefy reserves the right to assume the exclusive defense and control of any matter subject to indemnification by you, and you will not in any event settle any claim without the prior written consent of Memefy. This defense and indemnification obligation will survive this Agreement and your use of Memefy Services.
  This Agreement, together with the Privacy Notice at https://memebit.xyz/app/privacy , which is incorporated by reference, and any other legal notices published by Memefy on the Memefy Services, shall constitute the entire agreement between you and Memefy concerning the Memefy Services.
  If any provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect.
  No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and Memefy's failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision.
  Memefy reserves the right to amend this Agreement at any time and without notice, and it is your responsibility to review this Agreement for any changes. Your use of the Memefy Services following any amendment of this Agreement will signify your assent to and acceptance of its revised terms.
  
  YOU AND MEMEFY AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE MEMEFY SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.`,
  fr:`Bienvenue et merci de visiter et d'utiliser Memefy.
  Dernière mise à jour: 12 décembre 2021
  En accédant ou en utilisant l'un des services fournis par Memefy ou ses filiales, vous avez également accès, vous (collectivement avec Memefy, les «Parties») manifester votre intention et acceptez d'être lié par la présente convention de conditions d'utilisation («Accord»). Cet accord affecte vos droits et obligations légaux. Si vous n'acceptez pas d'être lié par cet accord, vous êtes expressément interdit d'accéder à ou d'utiliser les services. Après une modification, un remplacement ou une modification des termes du présent contrat, votre utilisation continue des services constitue votre accord sur ladite modification, remplacement ou modification.
  
  Éligibilité
  
  Les services ne sont disponibles que pour les personnes de plus de treize ans (13) et plus âgées, selon la plus grande. Les personnes de moins de 13 ans sont expressément interdites de créer un compte d'utilisateur ou d'utiliser autrement les services. Memefy peut fournir aux utilisateurs la possibilité de télécharger ou de transmettre du contenu à ou via les services, y compris, sans toutefois s'y limiter, l'engagement des utilisateurs. Lorsque vous soumettez l'engagement de l'utilisateur aux services, vous accordez à Memefy une licence non exclusive, irrévocable, mondiale et perpétuelle d'utiliser votre engagement de l'utilisateur pour les besoins des services habituels et destinés aux services. Ces objectifs peuvent inclure de vous fournir ou des tiers avec les services, la sauvegarde ou l'archivage des services et la vente ou le transfert des services à une tierce partie. En soumettant l'engagement des utilisateurs aux services, vous acceptez de renoncer à tous les droits moraux dans ou à votre engagement de l'utilisateur à travers le monde, que vous ayez ou non affirmé les droits moraux. Vous acceptez également de renoncer à tous les droits de la publicité ou de la confidentialité dans ou à votre engagement de l'utilisateur.
  Memefy n'est pas responsable de l'engagement des utilisateurs, du contenu tiers, du contenu syndiqué, des services, des publicités et / ou des liens pouvant figurer sur les services. Les services peuvent contenir des liens vers des sites Web tiers qui ne sont ni possédés ni contrôlés par Memefy. Memefy n'a aucun contrôle et n'assume aucune responsabilité pour, le contenu, les services, les politiques de confidentialité, les conditions d'utilisation ou les pratiques de tout site Web ou services tiers. De plus, Memefy ne peut et ne peut pas censurer ou éditer le contenu d'un site tiers. En utilisant les services, vous tenez expressément Memefy inoffensif à partir de tout responsable de votre utilisation de tout site Web tiers. Votre correspondance et vos relations commerciales avec des tiers trouvés à travers les services sont uniquement entre vous et la tierce partie.
  Vous acceptez que vous êtes responsable de toutes les données ou de tous les frais d'itinérance que vous encourez grâce à l'utilisation des services.
  Memefy interdit de ramper, de racler, de mettre en cache ou d'accéder autrement à tout contenu ou à un engagement de l'utilisateur sur le service Memefy via des moyens automatisés, sauf si possible de la suite de protocoles de moteur de recherche standard ou de technologies utilisées par un moteur de recherche avec le consentement de Memefy Express.
  Vous êtes seul responsable de vos interactions avec d'autres utilisateurs des services, qu'il soit en ligne ou hors ligne. Vous acceptez que Memefy n'est pas responsable ni responsable de la conduite d'un utilisateur. Memefy se réserve le droit, mais n'a aucune obligation de surveiller ou de s'impliquer dans des différends entre vous et d'autres utilisateurs.
  Il y aura des occasions lorsque les services peuvent être interrompus, y compris, sans limitation, pour la maintenance ou la mise à niveau prévus, pour des réparations d'urgence ou en raison de la défaillance des liens de télécommunication et / ou des équipements. Memefy ne pourrai être tenu responsable de ces interruptions.
  Memefy se réserve le droit de supprimer tout contenu et / ou engagement de l'utilisateur des services pour une raison quelconque, sans préavis. Le contenu et / ou l'engagement des utilisateurs retirés des services peuvent continuer à être stockés par Memefy, y compris, sans limitation, afin de se conformer à certaines obligations légales, mais ne peut être récupérable sans une ordonnance du tribunal valide. Memefy n'est pas un service de sauvegarde et vous acceptez que vous ne vous fierez pas sur les services aux fins de la sauvegarde ou du stockage de contenu. Memefy ne sera pas accusé pour une modification, une suspension ou une interruption des services Memefy ou la perte de tout contenu ou engagement de l'utilisateur. Vous reconnaissez également que Internet peut être soumis à des violations de la sécurité et que la soumission de l'engagement des utilisateurs ou d'autres informations peut ne pas être sécurisée. Vous êtes expressément et seul responsable de votre propre sécurité lors de l'utilisation des services.
  
  MemeBit vous fournit une licence limitée, non exclusive, non sublicieuse, non assignable et révocable, destinée à utiliser les services pour leurs objectifs habituels et destinés. L'utilisation des services d'utilisation en dehors de leurs objectifs habituels et prévus ou en violation des termes de cet accord entraînera la résiliation immédiate de cette licence. Cette licence est révocable à tout moment et tous les droits non expressément accordés ici sont réservés à MemeBit.
  Afin d'accéder à certaines fonctionnalités des services, vous devrez créer un compte. Vous n'utiliserez peut-être jamais un autre compte d'un autre utilisateur sans autorisation ni solliciter, collecter ou utiliser les informations d'identification de connexion des autres utilisateurs. Lors de la création de votre compte, vous devez fournir des informations précises et complètes. Vous êtes responsable de la sécurisation de votre mot de passe et que vous êtes seul responsable de l'activité qui se produit sur votre compte. Bien que MemeBit ne soit pas responsable des pertes causées par une utilisation non autorisée de votre compte, vous pouvez être tenu responsable des pertes de memebit ou d'autres personnes en raison de cette utilisation non autorisée. Si vous prenez conscience de toute violation de la sécurité ou de l'utilisation non autorisée de votre mot de passe ou de votre compte, vous devez en informer MemeBit immédiatement à support@memebit.xyz.
  Vous acceptez que vous ne vendrez, transférer, licenciez ou attribuerez votre compte, votre nom d'utilisateur ou tout droit de compte. Memefy interdit la création de, et vous acceptez que vous ne créez pas, un compte pour personne autre que vous-même.
  Vous acceptez également que toutes les informations que vous fournissez ou que vous avez fournies à Memefy lors de l'enregistrement et à toutes les autres fois sera vraie, exacte, actuelle et complète, et vous acceptez de mettre à jour vos informations si nécessaire pour maintenir sa vérité et sa précision.
  
  Utilisation des services - Autorisations et restrictions à votre utilisation
  
  Vous acceptez d'utiliser les services uniquement à des fins autorisées par le présent contrat. Memebit ici En vous accordent la permission d'accéder à l'accès et de l'utilisation des services énoncés dans le présent contrat, à condition que:
  Vous acceptez que vous ayez le droit légal et la capacité de conclure à cet accord dans votre juridiction.
  Vous ne devez pas utiliser les services pour un objectif illégal ou non autorisé. Vous acceptez de respecter toutes les lois, règles et règlements (par exemple, fédéral, État, local et provincial) applicable à votre utilisation des services et de votre engagement de votre utilisateur, y compris, sans toutefois s'y limiter, les lois sur le droit d'auteur et les lois à l'exportation.
  Vous ne devez pas publier de manière abusive, obscène, menaçante, harcène, diffamatoire, diffamatoire, offensante, violente, nue, partiellement nue, discriminatoire, illégale, violation, haineuse, pornographique ou sexuellement suggestive de l'utilisateur via les services, Vous ne devez pas poster du spam. Vous ne devez pas diffamer, la tige, l'intimidateur, la maltraitance, le harcèlement, menacer, imiter ou intimider des personnes ou des entités. Vous ne devez pas faire de fausses déclarations fausses ou trompeuses.
  Vous ne devez pas publier des informations privées, confidentielles ou sensibles, ni informations qui sont autrement violation de la loi via les e-services, y compris, sans limitation, votre ou toute autre personne d'information de carte de crédit, de la sécurité sociale ou des numéros d'identité nationale, des numéros de téléphone non publics, des adresses ou des adresses électroniques. Vous ne devez pas soumettre de matériel protégé par le droit d'auteur, protégé par un secret commercial ou autrement soumis à des droits de propriété tiers, y compris la vie privée et les droits de publicité, à moins que vous ne soyez propriétaire de ces droits ou que vous avez la permission de leur propriétaire légitime de poster le matériel et d'accorder à MemeBit.
  Vous devez garder tout votre engagement de votre utilisateur pertinent et "sur la rubrique" à l'élément de l'engagement de l'utilisateur ouvert pour les commentaires ou les soumissions.
  Vous ne devez pas distribuer dans aucun élément moyen des services sans autorisation écrite préalable de Memefy. Vous acceptez de ne pas contourner, désactiver ou interférerez-vous de manière à ne pas interférer avec des fonctionnalités relatives à la sécurité des services ou des fonctionnalités qui empêchent ou limiter l'utilisation ou la copie de tout contenu et engagement des utilisateurs ou appliquer des limitations sur l'utilisation des services et du contenu et de l'engagement des utilisateurs.
  Vous ne devez pas vous engager dans une activité qui interfère avec ou perturbe les services (ou les serveurs et les réseaux connectés aux services), y compris en transmettant des vers, des virus, des logiciels espions, des logiciels malveillants ou de tout autre code de nature destructeur ou perturbateur. Vous ne pouvez pas permettre d'injecter du contenu ou du code ni d'altérer ou d'interférer avec Memefy et ses services sauf par les moyens dont une partie des services est rendue ou affichée dans le navigateur ou le périphérique d'un utilisateur via une interface dédié par Memefy à cet effet.
  Vous ne devez pas changer, modifier ou modifier une partie des services pour une raison quelconque.
  Vous acceptez de ne pas utiliser ou lancer de type de système automatisé, y compris mais qui ne se limite pas à, "robots", "araignées", "araignées" ou "lecteurs hors ligne", qui accède aux services d'une manière qui envoie plus de messages de demande aux serveurs de Memebit dans une période donnée que la raison d'un humain peut Vous acceptez de ne pas accéder à (ni à essayer d'accéder à) les services, y compris le contenu et l'engagement de l'utilisateur, par n'importe quel moyen d'autres que par les interfaces fournies par MemeBit.
  Vous ne devez pas solliciter, à des fins commerciales, de spam ou d'envoyer des communications harcelantes à tous les utilisateurs. De plus, vous ne devez pas collecter ou récolter des informations personnelles des services.
  Vous ne devez pas tenter de limiter un autre utilisateur d'utiliser ou d'apprécier les services et vous ne devez pas encourager ni ne faciliter la violation de cet accord ni d'autres termes MEMEFY.
  Le contenu et la propriété intellectuelle Memefy, y compris, sans toutefois s'y limiter, les marques Memefy, les noms commerciaux et les logos, sur les services appartenant à Memefy, sous réserve du droit d'auteur et d'autres droits de propriété intellectuelle en vertu des États-Unis et des lois étrangères et internationales Le contenu sur les services peut ne pas être utilisé, copié, reproduit, distribué, transmis, diffusé, affiché, vendu, sous licence ou autrement exploité à d'autres fins sans le consentement écrit préalable des propriétaires respectifs. Memefy réserve tous les droits qui ne sont pas expressément accordés dans et aux services et au contenu.
  Vous acceptez de ne pas utiliser, copier ou distribuer, ni indirectement, aucun du contenu autre que celui qui est expressément autorisé ici, y compris toute utilisation, copie ou répartition de l'engagement des utilisateurs de tiers obtenus par le biais des services à des fins commerciales. Si vous téléchargez ou imprimez une copie du contenu et / ou de l'engagement de l'utilisateur pour une utilisation personnelle, vous devez conserver tous les droits d'auteur et les autres avis de propriété contenus. Vous acceptez que MemeBit ne tient aucune responsabilité pour le contenu affiché dans le service, y compris, sans toutefois s'y limiter, l'engagement des utilisateurs. Memefy n'est pas obligé de surveiller ou de modifier un contenu affiché sur Memefy, y compris, sans toutefois s'y limiter, engagement de l'utilisateur. Si votre contenu viole cet accord, vous pouvez assumer la responsabilité légale de ce contenu.
  Memefy se réserve le droit d'interrompre tout aspect des services, soit spécifiquement à vous, soit généralement à tout moment.
  Memefy peut mettre fin à l'accès d'un utilisateur aux services à tout moment, pour une raison quelconque. Si des suspects Memebit que vous avez violé toute disposition de cet accord, MemeBit peut également rechercher tout autre recours juridique disponible. Vos droits en vertu de la présente convention se termineront automatiquement si vous enfreignez une partie du présent contrat. En outre, Memebit se réserve le droit de refuser l'accès aux services à quiconque pour une raison quelconque à tout moment.
  
  Engagement de l'utilisateur
  
  Vous pouvez avoir la possibilité d'examiner et de poster des commentaires des utilisateurs sur les services. Vos commentaires de votre utilisateur doivent adhérer à la présente convention, tout mandat d'application mobile supplémentaire de magasin ou de marché sur lequel vous avez téléchargé de tels services et, dans la mesure du possible, applicables, étrangers, nationaux, étatiques ou locaux. Si un commentaire est effectué à l'aide de votre identité, il sera réputé avoir été posté par vous. MemeBit n'acceptera pas la responsabilité des commentaires des utilisateurs et d'autres informations publiées dans les commentaires. Si MemeBit reçoit un avis que tous les commentaires d'utilisateur ne sont pas conformes à la présente convention ou à l'utilisation prévue des commentaires des utilisateurs, Memezit peut supprimer ces commentaires d'utilisateur. De plus, une telle conduite peut vous entraîner et / ou votre compte étant interdit des services.
  Les commentaires des utilisateurs sont mis à votre disposition pour votre information et votre utilisation personnelle uniquement comme prévu dans la fonctionnalité normale des services. Les commentaires des utilisateurs sont mis à la disposition de l'utilisateur et ne peuvent pas être utilisés, copiés, reproduits, affichés, vendus, licenciés, téléchargés, distribués, transmis, diffusés ou non exploités de quelque manière que ce soit de la fonctionnalité normale des services ou non expressément autorisés dans le présent Accord.
  Vous possédez ou avez les licences, les droits, les consentements nécessaires et les autorisations nécessaires à l'utilisation et à nous autoriser à utiliser tous les brevets, marques commerciales, commerce de commerce, droit d'auteur ou autres droits exclusifs dans et à toutes les soumissions utilisateur afin de permettre l'inclusion et l'utilisation des soumissions de l'utilisateur de la manière CLOSPL.
  Vous avez le consentement écrit, la libération et / ou la permission de chaque personne identifiante identifiable dans la soumission de l'utilisateur pour utiliser le nom ou la ressemblance de chaque personne identifiable de ce type pour permettre l'inclusion et l'utilisation des soumissions de l'utilisateur de la manière envisagée par les services et cet accord.
  Vous affirmez, déclarez et garantissez en outre que la publication et l'utilisation de votre engagement d'utilisateur sur ou via les services Memefy ne viole pas, ne détourne pas ou n'enfreint pas les droits de tiers, y compris, sans limitation, les droits de confidentialité, les droits de publicité, les droits d'auteur , marque déposée et/ou autres droits de propriété intellectuelle.
  Vous acceptez de payer pour toutes les redevances, les frais et les autres sommes dus à la raison de votre engagement de l'utilisateur que vous postez sur ou via les services.
  Memefy n'approuve aucun engagement de l'utilisateur ni aucun avis, recommandation ou conseil exprimé dans celui-ci, et MemeBit décline expressément toute responsabilité dans le cadre de l'engagement des utilisateurs. Memefy n'autorise pas le droit d'auteur des activités de violation des droits d'auteur et de la violation des droits de propriété intellectuelle sur ses services et Memefy supprimera tout le contenu et l'engagement des utilisateurs si cela a été correctement informé que ce contenu ou l'engagement de l'utilisateur enfreint les droits de propriété intellectuelle. Memefy peut, mais n'a aucune obligation de, supprimer, modifier, bloquer et / ou surveiller l'engagement des utilisateurs ou les comptes contenant l'engagement des utilisateurs que Memefy détermine dans sa seule discrétion viole le présent accord. Memefy mettra également fin à l'accès d'un utilisateur aux services, s'ils sont déterminés à être un contrefaction répété. Un contrefaction répétée est un utilisateur qui a été informé de l'activité de contrefaçon plus de deux fois et / ou a eu l'engagement de l'utilisateur supprimé des services plus de deux fois.
  Memefy se réserve le droit de déterminer à sa seule discrétion si le contenu ou l'engagement de l'utilisateur est approprié et conforme à la présente convention de violation autre que la violation des droits d'auteur et des violations du droit de la propriété intellectuelle, y compris, mais sans se limiter à la pornographie ou au matériel de pornographie, à la haine Memefy peut, à tout moment, sans préavis et à sa seule discrétion, supprimez cet engagement de l'utilisateur et / ou de mettre fin à l'accès d'un utilisateur pour la soumissionne de ce matériel en violation de la présente convention.
  Vous comprenez que lorsque vous utilisez les services, vous serez exposé à l'engagement de l'utilisateur à partir de diverses sources. Memefy n'est pas responsable des droits de protection, d'utilité, de sécurité ou de propriété intellectuelle de ou de cet engagement de l'utilisateur. Vous comprenez et acceptez que MemeBit ne puisse pas et ne sera pas responsable de l'engagement de l'utilisateur affiché sur les services et que vous utilisez les services à vos risques et périls.
  Memefy peut vous fournir la possibilité de partager votre emplacement géographique avec MemeBit et d'autres utilisateurs des services lors de l'utilisation des services. Vous pouvez également accepter ou rejeter toutes les demandes d'utilisateurs des services pour obtenir votre lieu géographique via les services. Si vous partagez votre lieu géographique avec vos abonnés, vous comprenez et acceptez que votre emplacement géographique peut apparaître sur une carte et que les abonnés à votre compte MemeBit peuvent être en mesure de déterminer votre emplacement physique exact. Si vous utilisez les services pour poster l'engagement de l'utilisateur à la fonction Memefy Carte située dans les services, vous comprenez et acceptez que votre emplacement géographique peut apparaître sur une carte et que tous les utilisateurs de la fonction MemeBit Carte située dans les services peuvent être en mesure de déterminer votre emplacement physique exact et physique. MemeBit vous offre la possibilité d'opter et de vous désinscrire de partager votre emplacement géographique dans les paramètres de votre appareil mobile et / ou de votre navigateur Web, ce qui peut vous fournir plusieurs options pour le partage de votre emplacement géographique, telles qu`
}